baseURL = "https://guyana-news-blog.pages.dev/"
languageCode = "en-us"
title = "Funny Take On Guyana Daily News"
theme = "PaperMod"

paginate = 10
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Your daily dose of Guyana news with humor"
  author = "Albert Massay"
  ShowShareButtons = true
  ShowReadingTime = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
