baseURL = "https://silly-cajeta-959f3e.netlify.app/"
languageCode = "en-us"
title = "Funny Take On Guyana News"
theme = "PaperMod"

[pagination]
pagerSize = 10

enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Your daily dose of Guyana news with humor"
  author = "Albert Massay"
  ShowShareButtons = true
  ShowReadingTime = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
