[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.122.0"

[context.production.environment]
  HUGO_ENV = "production"
